##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # redis
  redis:
    image: ${IMAGE_REPO}/${IMAGE_REDIS}
    container_name: "redis.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "redis.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/redis/conf/redis.conf:/etc/redis/redis.conf:ro
      - ./volume/redis/data:/data:rw
    network_mode: "host"
    extra_hosts:
      - "redis.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
